### ISSUE TITLE
Build failure with GHC 7.10.1-rc1

### ISSUE THREAD

**Issue by peti** [pepeiborra/control-monad-free#3]
Hi, I'm trying to compile `hledger` with the current GHC 7.10.1 release candidate, but I've run into trouble with `control-monad-free` because of the issues indicated by the following GHC 7.8.4 warnings:

```
Control/Monad/Free.hs:58:10: Warning:
    ‘Free’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.

Control/Monad/Free.hs:111:10: Warning:
    ‘FreeT’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[2 of 3] Compiling Control.Monad.Free.Zip ( Control/Monad/Free/Zip.hs, dist/build/Control/Monad/Free/Zip.o )
[3 of 3] Compiling Control.Monad.Free.Improve ( Control/Monad/Free/Improve.hs, dist/build/Control/Monad/Free/Improve.o )

Control/Monad/Free/Improve.hs:36:10: Warning:
    ‘C’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.

Control/Monad/Free/Improve.hs:44:10: Warning:
    ‘C’ is an instance of MonadPlus but not Alternative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
```

Would it be possible to get an updated version of your package that remedies these issues?

**Comment by pepeiborra** [comment]
Sure, I'll take a look tonight

**Comment by pepeiborra** [comment]
Control-monad-free 0.6.0 is up, tested with ghc 7.8.3

**Comment by peti** [comment]
GHC 7.10.1-rc1 isn't happy about `control-monad-free-0.6.0.1`, I'm afraid:

    Control/Monad/Free.hs:159:10:
        Could not deduce (Alternative (FreeT f m))
          arising from the superclasses of an instance declaration
        from the context (Functor f, Monad m, MonadPlus m)
          bound by the instance declaration
          at Control/Monad/Free.hs:159:10-67
        In the instance declaration for ‘MonadPlus (FreeT f m)’

GHC 7.8.4 issues [the following warnings](http://hydra.cryp.to/build/519651/log/raw):

    [1 of 3] Compiling Control.Monad.Free ( Control/Monad/Free.hs, dist/build/Control/Monad/Free.o )

    Control/Monad/Free.hs:159:10: Warning:
        ‘FreeT’ is an instance of MonadPlus but not Alternative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
    [2 of 3] Compiling Control.Monad.Free.Zip ( Control/Monad/Free/Zip.hs, dist/build/Control/Monad/Free/Zip.o )
    [3 of 3] Compiling Control.Monad.Free.Improve ( Control/Monad/Free/Improve.hs, dist/build/Control/Monad/Free/Improve.o )

    Control/Monad/Free/Improve.hs:53:10: Warning:
        ‘C’ is an instance of MonadPlus but not Alternative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.

**Comment by peti** [comment]
More compiler warnings from GHC 7.10.1-rc1 that might be of interest:

    on the commandline: Warning:
        -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

**Comment by pepeiborra** [comment]
Thanks, that's very helpful.  Version 0.6.1 is up with the missing
Alternative instances. If I can get around to download 7.10 then I'll sort
out the use of -XOverlappingInstances as well
