### ISSUE TITLE
control-monad-free-0.6.0.1 doesn't compile with GHC 7.6.3

### ISSUE THREAD

**Issue by peti** [pepeiborra/control-monad-free#4]
The compiler complains:

```
Control/Monad/Free.hs:45:67:
    Can't make a derived instance of `Typeable (Free f a)':
      `Free' must only have arguments of kind `*'
    In the data declaration for `Free'
```

A complete build log is at http://hydra.cryp.to/build/520220/nixlog/2/raw.

**Comment by thdox** [comment]
Linux Debian next stable release, to be pusblished 25-Apr-2015, is delivered with GHC 7.6.3. 
I get the same error while compiling. Thus preventing installing any dependency like hledger.
Is there any workaround?

**Comment by pepeiborra** [comment]
Version 0.6.0 inadvertently broke compatibility with ghc 7.6.x, and I am afraid there is no work around until Debian updates to ghc 7.8.x. I can release a new version of control-monad-free which restores compatibility, if that helps.
I don't claim to understand the Debian release process, but I would have thought they'd test compatibility before upgrading a library ?

**Comment by thdox** [comment]
@pepeiborra, thanks for you answer, it helped me finding a workaround.

Debian Jessie is delivered with ghc 7.6.3. And actually I found that there is also libghc-control-monad-free-dev-0.5.3 that is delivered. So after installing the latter, I managed to successfully "cabal install  hledger".

**Comment by simonmichael** [comment]
In some cases, you'll be able to work around this by specifying an older version of the package:
```
cabal install --constraint 'control-monad-free < 0.6' ...
```

**Comment by thdox** [comment]
I confirm that workaround proposed by @simonmichael does work.
